services:
  - docker

sudo: required

branches:
  only:
  - master

before_install:
  #Update docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  - /bin/bash build-docker-image.sh
  - |
      ##################################################################
      #If DOCKER_REGISTRY, DOCKER_USER, and DOCKER_PASSWORD are given
      #then login to the DOCKER_REGISTRY, and upload the image
      ##################################################################

      REPO_NAME="gslc"

      ##################################################################
      # Get the version
      ##################################################################

      GIT_TAG=`git rev-parse HEAD`
      if [ ! -z "$TRAVIS_COMMIT" ]; then
        GIT_TAG=$TRAVIS_COMMIT
      fi
      GIT_TAG=${GIT_TAG:0:8}
      PACKAGE_VERSION=$GIT_TAG
      echo "DOCKER_USER=$DOCKER_USER"
      echo "DOCKER_REGISTRY=$DOCKER_REGISTRY"
      echo "TRAVIS=$TRAVIS"
      echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
      echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"

      if [[ (("$TRAVIS" == "true" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false") || "$TRAVIS" != "true") && ! -z  $DOCKER_USER && ! -z  $DOCKER_PASSWORD && ! -z  $DOCKER_REGISTRY ]]; then
        docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY

        #quay.io robot accounts are the name+robotname. We need to cut
        #the "+robotname" off for naming the image
        DOCKER_IMAGE_USER=$(echo "$DOCKER_USER" | sed 's/+.*//')
        echo "DOCKER_IMAGE_USER=$DOCKER_IMAGE_USER"

        docker tag $REPO_NAME:$PACKAGE_VERSION $DOCKER_REGISTRY/$DOCKER_IMAGE_USER/$REPO_NAME:$PACKAGE_VERSION
        echo "Pushing $DOCKER_REGISTRY/$DOCKER_IMAGE_USER/$REPO_NAME:$PACKAGE_VERSION"
        docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_USER/$REPO_NAME:$PACKAGE_VERSION
      fi
