#!/usr/bin/env bash
# Builds and tests the latest amyris master

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GSLC_AMYRIS="GslcAmyris"

if [ ! -d $DIR/$GSLC_AMYRIS ]; then
	echo "$DIR/$GSLC_AMYRIS not there"
	cd $DIR
	git clone git@github.com:AmyrisInc/Gslc.git $GSLC_AMYRIS
fi

cd $DIR/$GSLC_AMYRIS
cp ../../Dockerfile .

# Get the version
GIT_TAG=`git rev-parse HEAD`
if [ ! -z "$TRAVIS_COMMIT" ]; then
	GIT_TAG=$TRAVIS_COMMIT
fi
GIT_TAG=${GIT_TAG:0:8}
VERSION=$GIT_TAG

DOCKER_IMAGE="gsl_amyris:$VERSION"
docker build -t $DOCKER_IMAGE .

COMAND="docker run --rm -ti $DOCKER_IMAGE find / -iname Gslc.exe"
# eval "$COMAND --version"
eval "$COMAND"
